Description: >
  Anas Hassan / CD using CircleCi pipeline, AWS CloudFormation and Ansible

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  ProjectName:
    Description: A Project name that will be used to mark resources for remote configuration
    Type: String

Resources:
  WebApp:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: GP-user_keyPairs
      ImageId: ami-0747bdcabd34c712a
      InstanceType: t2.small
      Monitoring: true
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN
      SecurityGroupIds:
        - Ref: WebServerSecGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-webServer
        - Key: Project
          Value: !Ref ProjectName

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
