---
- name: Set up an ubuntu Public EC2 provisioned by circleci and cloudformation
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      ansible.builtin.wait_for_connection:
        timeout: 300
  roles:
    - config-infra
